### ISSUE TITLE
起服务器的命令还有数据库的命令是啥呀

### ISSUE THREAD

**Issue by Adherentman** [Nealyang/React-Express-Blog-Demo#1]
起服务器的命令还有数据库的命令是啥呀

**Comment by Nealyang** [comment]
安装相应依赖后，确保本机安装了mongodb数据。端口为默认端口。
命令全部在package.json中配置的。
npm  start  
启动开发

**Comment by Italic-2012** [comment]
其项目的时候报了这样的错误，何解？ 
Error: connect ECONNREFUSED 127.0.0.1:3030
    at Object.exports._errnoException (util.js:1016:11)
    at exports._exceptionWithHostPort (util.js:1039:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1138:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react_express_blog@1.0.0 watch-client: `cross-env NODE_ENV=development node ./server/index.js `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react_express_blog@1.0.0 watch-client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2017-10-10T06_45_47_196Z-debug.log

**Comment by Nealyang** [comment]
@Italic-2012 这个是因为本机3030端口被占用了吧

**Comment by Italic-2012** [comment]
@Nealyang 这个项目有需要用到3030端口？

**Comment by Nealyang** [comment]
@Italic-2012 关于端口的配置，可以看下config/config.js文件。如果占用了3030端口，就修改下这个配置文件或者杀死占用端口的进程

**Comment by Italic-2012** [comment]
@Nealyang 我更改了端口，还是不行

**Comment by Nealyang** [comment]
@Italic-2012 如果还是报错connect ECONNREFUSED，查看下本地端口占用情况

**Comment by Italic-2012** [comment]
@Nealyang 我填的是没有占用的端口，还是不行

**Comment by Nealyang** [comment]
@Italic-2012 报错信息呢

**Comment by Italic-2012** [comment]
Error: connect ECONNREFUSED 127.0.0.1:3030
at Object.exports._errnoException (util.js:1016:11)
at exports._exceptionWithHostPort (util.js:1039:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1138:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react_express_blog@1.0.0 watch-client: cross-env NODE_ENV=development node ./server/index.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react_express_blog@1.0.0 watch-client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Administrator\AppData\Roaming\npm-cache_logs\2017-10-10T06_45_47_196Z-debug.log

这不是么

**Comment by luoxiaofeng369** [comment]
跟楼上一样  改了config/config.js端口 还是没有用 ， 检查了本地端口  这个端口被node.exe 占用    求解决~

**Comment by Nealyang** [comment]
@luoxiaofeng369 确定端口号没有被占用，分两个DOS分别执行package.json中start的命令，确保启动server的时候api服务器已经启动成功

**Comment by luoxiaofeng369** [comment]
"start": "npm run watch-client & npm run start-dev-api"     分开启动要先启动后面的这段
 npm run start-dev-api
 再启动 前面的
npm run watch-client

谢 博主

**Comment by Italic-2012** [comment]
![image](https://user-images.githubusercontent.com/24502019/32262731-4113548e-bf11-11e7-9c9e-56e5721f349e.png)之前的文章呢。。。

**Comment by Nealyang** [comment]
导入我共享出来的数据库，就可以了。

ps：这个issue已经关闭了，新起一个吧
