### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:3030

### ISSUE THREAD

**Issue by laimeifeng** [Nealyang/React-Express-Blog-Demo#12]
你好，非常感谢你Blog的开源，
  我 git clone了你的项目，安装了依赖，初始化了mongodb的admin/admin，
    然后进行npm start，出现了一个错误
       在弹出的http://127.0.0.1:3000/页面，出现网络连接错误。
           输出的信息表示是数据权限错误，不能连接到127.0.0.1:3030
                 下面是我cmd的输出信息，请问怎么样解决这个问题呢？
----------------------------------------------------------------------------------------------------------------------C:\Users\lenovo\Desktop\React-Express-Blog-Demo>npm start

> react_express_blog@1.0.0 start C:\Users\lenovo\Desktop\React-Express-Blog-Demo

> npm run watch-client & npm run start-dev-api

> react_express_blog@1.0.0 watch-client C:\Users\lenovo\Desktop\React-Express-Bl
og-Demo
> cross-env NODE_ENV=development node ./server/index.js

C:\Users\lenovo\Desktop\React-Express-Blog-Demo\app\index.js
clean-webpack-plugin: C:\Users\lenovo\Desktop\React-Express-Blog-Demo\build has
been removed.
  build [=         ] 10%===>open http://127.0.0.1:3000 in a browser to view the
app
  build [==        ] 15%webpack: wait until bundle finished: /__webpack_hmr
Build completed in 42.499s

webpack built df36efa870cb7f0046d2 in 42497ms
Hash: df36efa870cb7f0046d2
Version: webpack 3.10.0
Time: 42497ms
                                Asset       Size  Chunks                    Chun
k Names
 d02fe8e3725c82dc54a287cf3b11039e.png     986 kB          [emitted]  [big]
 b2299473f5628502c981b5a381307646.png    9.25 kB          [emitted]
 cddb5f2e8bc3caa6d0596f66274d54d5.jpg    12.2 kB          [emitted]
 f26996dee7e34d4f043302efa66f184a.png     888 kB          [emitted]  [big]
 8f0078d321fdb9ab666606bbe0a1d929.png    1.33 MB          [emitted]  [big]
 c95d7b3c64e890326489e808d77d8941.jpg    38.4 kB          [emitted]
90a6f773e5a34a9a0ad0818b98511dd7.jpeg    9.69 kB          [emitted]
                   vendor-df36efa8.js    9.17 MB       0  [emitted]  [big]  vend
or
                    index-df36efa8.js     763 kB       1  [emitted]  [big]  inde
x
                 manifest-df36efa8.js    31.2 kB       2  [emitted]         mani
fest
                           index.html  329 bytes          [emitted]
[2twT] ./app/index.js 1.57 kB {1} [built]
[3Sk7] ./node_modules/react-hot-loader/patch.js 40 bytes {0} [built]
[3r6y] ./node_modules/react-router-dom/es/NavLink.js 2.66 kB {0} [built]
[4M2W] ./node_modules/core-js/shim.js 8.18 kB {0} [built]
[52Em] ./node_modules/react-router-dom/es/Prompt.js 131 bytes {0} [built]
[F8kA] ./node_modules/react-router-dom/es/index.js 925 bytes {0} [built]
[O27J] ./node_modules/react-dom/index.js 59 bytes {0} [built]
[PGPo] ./node_modules/react-router-dom/es/Redirect.js 137 bytes {0} [built]
[R1Tp] (webpack)-hot-middleware/client.js?path=http://127.0.0.1:3000/__webpack_h
mr 7.35 kB {0} [built]
[RH2O] ./node_modules/react-redux/es/index.js 230 bytes {0} [built]
[U7vG] ./node_modules/react/react.js 56 bytes {0} [built]
   [0] multi react-hot-loader/patch webpack-hot-middleware/client?path=http://12
7.0.0.1:3000/__webpack_hmr babel-polyfill ./app/index.js 64 bytes {1} [built]
   [1] multi react react-dom react-router-dom 52 bytes {0} [built]
[dCLN] ./node_modules/react-router-dom/es/Router.js 131 bytes {0} [built]
[j1ja] ./node_modules/babel-polyfill/lib/index.js 833 bytes {0} [built]
    + 1504 hidden modules
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks  Chunk Names
    index.html  1.45 MB       0
    [3IRH] (webpack)/buildin/module.js 517 bytes {0} [built]
    [DuR2] (webpack)/buildin/global.js 509 bytes {0} [built]
    [M4fF] ./node_modules/lodash/lodash.js 540 kB {0} [built]
    [a/t9] ./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/html-
webpack-plugin/default_index.ejs 538 bytes {0} [built]
webpack: Compiled successfully.
C:\Users\lenovo\Desktop\React-Express-Blog-Demo\node_modules\http-proxy\lib\http
-proxy\index.js:119
    throw err;
    ^

Error: connect ECONNREFUSED 127.0.0.1:3030
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react_express_blog@1.0.0 watch-client: `cross-env NODE_ENV=development
node ./server/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react_express_blog@1.0.0 watch-client script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\AppData\Roaming\npm-cache\_logs\2017-12-11T14_21_49
_855Z-debug.log

> react_express_blog@1.0.0 start-dev-api C:\Users\lenovo\Desktop\React-Express-B
log-Demo
> nodemon --watch server/api server/api/index.js

[nodemon] 1.12.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: C:\Users\lenovo\Desktop\React-Express-Blog-Demo\server\api/*
*/*
[nodemon] starting `node server/api/index.js`
(node:16260) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, u
se `openUri()` instead, or set the `useMongoClient` option if using `connect()`
or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mon
go-client
数据库连接成功
===> api server is running at 127.0.0.1:3030
-------------------------------------------------------------------------------------------------------------------

**Comment by Nealyang** [comment]
你的npm配置代理了么？如果配置了代理，可能是代理有问题，npm config set proxy null ，然后将start中的命令分两个DOS窗口启动，注意先启动server端

**Comment by XHanW** [comment]
怎么初始化mongodb的admin/admin，没用过数据库小白，可以指点吗？
