### ISSUE TITLE
请问我要怎么执行生产环境下的打包配置文件？

### ISSUE THREAD

**Issue by forturegrant** [Nealyang/React-Express-Blog-Demo#13]
这里start-prod，可是并没有bin/server这个文件夹啊

**Comment by forturegrant** [comment]
"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start-prod": "cross-env NODE_ENV=production node bin/server",
    "start-dev-api": "node server/api server/api/index.js",
    "watch-client": "cross-env NODE_ENV=development node ./server/index.js",
    "start": "concurrently \"npm run start-dev-api\" \"npm run watch-client\""
  },

**Comment by Nealyang** [comment]
生产环境下的webpack配置文件写好了，但是没有测试过，package.json中应该没有配置，你可以自己研究下，webpack配置文件肯定比开发环境的简单
