### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by Butonix** [Nealyang/React-Express-Blog-Demo#14]
C:\Users\rever\Desktop\React-Express-Blog-Demo-master>npm start

> react_express_blog@1.0.0 start C:\Users\rever\Desktop\React-Express-Blog-Demo-master
> npm run watch-client & npm run start-dev-api

> react_express_blog@1.0.0 watch-client C:\Users\rever\Desktop\React-Express-Blog-Demo-master
> cross-env NODE_ENV=development node ./server/index.js

C:\Users\rever\Desktop\React-Express-Blog-Demo-master\app\index.js
clean-webpack-plugin: C:\Users\rever\Desktop\React-Express-Blog-Demo-master\build has been removed.
  build [==                  ] 10%===>open http://127.0.0.1:3000 in a browser to view the app
  build [=======             ] 35%webpack: wait until bundle finished: /index.html
Build completed in 17.371s

webpack built 4901e96648c0ec792123 in 17374ms
Hash: 4901e96648c0ec792123
Version: webpack 3.10.0
Time: 17374ms
                                Asset       Size  Chunks                    Chunk Names
 b2299473f5628502c981b5a381307646.png    9.25 kB          [emitted]
 cddb5f2e8bc3caa6d0596f66274d54d5.jpg    12.2 kB          [emitted]
 f26996dee7e34d4f043302efa66f184a.png     888 kB          [emitted]  [big]
 8f0078d321fdb9ab666606bbe0a1d929.png    1.33 MB          [emitted]  [big]
 d02fe8e3725c82dc54a287cf3b11039e.png     986 kB          [emitted]  [big]
 c95d7b3c64e890326489e808d77d8941.jpg    38.4 kB          [emitted]
90a6f773e5a34a9a0ad0818b98511dd7.jpeg    9.69 kB          [emitted]
                   vendor-4901e966.js    9.17 MB       0  [emitted]  [big]  vendor
                    index-4901e966.js     732 kB       1  [emitted]  [big]  index
                 manifest-4901e966.js    31.2 kB       2  [emitted]         manifest
                           index.html  329 bytes          [emitted]
[2twT] ./app/index.js 1.59 kB {1} [built]
[3IRH] (webpack)/buildin/module.js 517 bytes {0} [built]
[3Sk7] ./node_modules/react-hot-loader/patch.js 40 bytes {0} [built]
[6cJI] ./node_modules/react-router-dom/es/Switch.js 131 bytes {0} [built]
[9uhF] ./node_modules/react-router-dom/es/StaticRouter.js 149 bytes {0} [built]
[F8kA] ./node_modules/react-router-dom/es/index.js 925 bytes {0} [built]
[O27J] ./node_modules/react-dom/index.js 59 bytes {0} [built]
[PGPo] ./node_modules/react-router-dom/es/Redirect.js 137 bytes {0} [built]
[R1Tp] (webpack)-hot-middleware/client.js?path=http://127.0.0.1:3000/__webpack_hmr 7.35 kB {0} [built]
[U7vG] ./node_modules/react/react.js 56 bytes {0} [built]
[j1ja] ./node_modules/babel-polyfill/lib/index.js 833 bytes {0} [built]
[tfLY] ./node_modules/react-router-dom/es/withRouter.js 143 bytes {0} [built]
[zkX4] ./node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js 24.4 kB {0} [built]
   [0] multi react-hot-loader/patch webpack-hot-middleware/client?path=http://127.0.0.1:3000/__webpack_hmr babel-polyfill ./app/index.js 64 bytes {1} [built]
   [1] multi react react-dom react-router-dom 52 bytes {0} [built]
    + 1505 hidden modules
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks  Chunk Names
    index.html  1.45 MB       0
    [3IRH] (webpack)/buildin/module.js 517 bytes {0} [built]
    [DuR2] (webpack)/buildin/global.js 509 bytes {0} [built]
    [M4fF] ./node_modules/lodash/lodash.js 540 kB {0} [built]
    [a/t9] ./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/html-webpack-plugin/default_index.ejs 538 bytes {0} [built]
webpack: Compiled successfully.
C:\Users\rever\Desktop\React-Express-Blog-Demo-master\node_modules\http-proxy\lib\http-proxy\index.js:119
    throw err;
    ^

Error: connect ECONNREFUSED 127.0.0.1:3030
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react_express_blog@1.0.0 watch-client: `cross-env NODE_ENV=development node ./server/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react_express_blog@1.0.0 watch-client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rever\AppData\Roaming\npm-cache\_logs\2017-12-17T14_11_57_370Z-debug.log

> react_express_blog@1.0.0 start-dev-api C:\Users\rever\Desktop\React-Express-Blog-Demo-master
> nodemon --watch server/api server/api/index.js

[nodemon] 1.13.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: C:\Users\rever\Desktop\React-Express-Blog-Demo-master\server\api/**/*
[nodemon] starting `node server/api/index.js`
(node:6368) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
数据库连接成功
===> api server is running at 127.0.0.1:3030

**Comment by Nealyang** [comment]
#10

**Comment by zhangguangbo111** [comment]
root@iZwz9fpoco9pnafnfdfdmbZ:/usr/local/React-Express-Blog-Demo# npm start

> react_express_blog@1.0.0 start /usr/local/React-Express-Blog-Demo
> npm run watch-client & npm run start-dev-api


> react_express_blog@1.0.0 start-dev-api /usr/local/React-Express-Blog-Demo
> nodemon --watch server/api server/api/index.js


> react_express_blog@1.0.0 watch-client /usr/local/React-Express-Blog-Demo
> cross-env NODE_ENV=development node ./server/index.js

[nodemon] 1.14.11
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /usr/local/React-Express-Blog-Demo/server/api/**/*
[nodemon] starting `node server/api/index.js`
/usr/local/React-Express-Blog-Demo/app/index.js
clean-webpack-plugin: /usr/local/React-Express-Blog-Demo/build has been removed.
  build [==                  ] 10%===>open http://127.0.0.1:3000 in a browser to view the app
(node:20717) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
数据库连接成功
===> api server is running at 127.0.0.1:3030
Build completed in 18.127s

webpack built 753f40c8af839a849ba4 in 18137ms
Hash: 753f40c8af839a849ba4
Version: webpack 3.10.0
Time: 18137ms
                                Asset       Size  Chunks                    Chunk Names
 b2299473f5628502c981b5a381307646.png    9.25 kB          [emitted]         
 cddb5f2e8bc3caa6d0596f66274d54d5.jpg    12.2 kB          [emitted]         
 f26996dee7e34d4f043302efa66f184a.png     888 kB          [emitted]  [big]  
 8f0078d321fdb9ab666606bbe0a1d929.png    1.33 MB          [emitted]  [big]  
 d02fe8e3725c82dc54a287cf3b11039e.png     986 kB          [emitted]  [big]  
 c95d7b3c64e890326489e808d77d8941.jpg    38.4 kB          [emitted]         
90a6f773e5a34a9a0ad0818b98511dd7.jpeg    9.69 kB          [emitted]         
                   vendor-753f40c8.js    9.17 MB       0  [emitted]  [big]  vendor
                    index-753f40c8.js     729 kB       1  [emitted]  [big]  index
                 manifest-753f40c8.js    31.2 kB       2  [emitted]         manifest
                           index.html  329 bytes          [emitted]         
[2twT] ./app/index.js 1.53 kB {1} [built]
[3IRH] (webpack)/buildin/module.js 517 bytes {0} [built]
[3Sk7] ./node_modules/react-hot-loader/patch.js 40 bytes {0} [built]
[6cJI] ./node_modules/react-router-dom/es/Switch.js 131 bytes {0} [built]
[9uhF] ./node_modules/react-router-dom/es/StaticRouter.js 149 bytes {0} [built]
[F8kA] ./node_modules/react-router-dom/es/index.js 925 bytes {0} [built]
[O27J] ./node_modules/react-dom/index.js 59 bytes {0} [built]
[PGPo] ./node_modules/react-router-dom/es/Redirect.js 137 bytes {0} [built]
[R1Tp] (webpack)-hot-middleware/client.js?path=http://127.0.0.1:3000/__webpack_hmr 7.35 kB {0} [built]
[U7vG] ./node_modules/react/react.js 56 bytes {0} [built]
[j1ja] ./node_modules/babel-polyfill/lib/index.js 833 bytes {0} [built]
[tfLY] ./node_modules/react-router-dom/es/withRouter.js 143 bytes {0} [built]
[zkX4] ./node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js 24.4 kB {0} [built]
   [0] multi react-hot-loader/patch webpack-hot-middleware/client?path=http://127.0.0.1:3000/__webpack_hmr babel-polyfill ./app/index.js 64 bytes {1} [built]
   [1] multi react react-dom react-router-dom 52 bytes {0} [built]
    + 1505 hidden modules
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks  Chunk Names
    index.html  1.45 MB       0  
    [3IRH] (webpack)/buildin/module.js 517 bytes {0} [built]
    [DuR2] (webpack)/buildin/global.js 509 bytes {0} [built]
    [M4fF] ./node_modules/lodash/lodash.js 540 kB {0} [built]
    [a/t9] ./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/html-webpack-plugin/default_index.ejs 538 bytes {0} [built]
webpack: Compiled successfully.
/usr/local/React-Express-Blog-Demo/node_modules/open-browser-webpack-plugin/index.js:46
        if (err) throw err;
                 ^

Error: Command failed: /usr/local/React-Express-Blog-Demo/node_modules/open/vendor/xdg-open "http://127.0.0.1:3000"
/usr/local/React-Express-Blog-Demo/node_modules/open/vendor/xdg-open: 1: /usr/local/React-Express-Blog-Demo/node_modules/open/vendor/xdg-open: xdg-mime: not found
xdg-open: no method available for opening 'http://127.0.0.1:3000'

    at ChildProcess.exithandler (child_process.js:272:12)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at Socket.emit (events.js:160:13)
    at Pipe._handle.close [as _onclose] (net.js:559:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react_express_blog@1.0.0 watch-client: `cross-env NODE_ENV=development node ./server/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react_express_blog@1.0.0 watch-client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-23T03_45_19_476Z-debug.log

**Comment by Nealyang** [comment]
connect ECONNREFUSED一般为node进程没有关闭，建议先确认下，然后win上的话，start下的命令分开跑，先起Server

**Comment by jasonapex** [comment]
我也是以上情况……

**Comment by IHongTaoI** [comment]
me too

**Comment by IHongTaoI** [comment]
怎么没数据，怎么导入数据
