### ISSUE TITLE
运行报以下这个错误

### ISSUE THREAD

**Issue by fxn9801** [Nealyang/React-Express-Blog-Demo#2]
非常感谢你可以开源，看你的代码。学习了好多东西呢。

./src/containers/home/components/login/LoginForm.js
  Line 4:  Import in body of module; reorder to top  import/first

Search for the keywords to learn more about each error.

**Comment by fxn9801** [comment]
解决了。将import换到前面就好了

**Comment by Nealyang** [comment]
不客气，一起学习一起进步~
