### ISSUE TITLE
CPU占用太高

### ISSUE THREAD

**Issue by nitrohe** [Nealyang/React-Express-Blog-Demo#25]
博主，npm start之后，cpu就达到100%（win7 64、10G内存），把除了浏览器和两个启动的cmd窗口之外的应用都关了

**Comment by nitrohe** [comment]
看了一下进程，node.exe的cpu占用80%到90%

**Comment by Hasaki1997** [comment]
用的什么编辑器

**Comment by Nealyang** [comment]
一直在忙工作，这个问题也是不少人反应，一直没有review代码。多谢！
