### ISSUE TITLE
req.session.userInfo为undefined

### ISSUE THREAD

**Issue by 17875057941** [Nealyang/React-Express-Blog-Demo#29]
博主你好请教一下，使用express-session设置了session，但是浏览器的application下的cookies仍然为空，req.session.userInfo为undefined。只有发送一个登陆请求到后端时，在对应的请求文件下才有cookies，但刷新后又会消失。希望博主指点一下

**Comment by Nealyang** [comment]
确定下是否因为跨域的问题导致的
