### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by xxyGoTop** [Nealyang/React-Express-Blog-Demo#3]
能否说明下 生产环境的部署  thank you

**Comment by Nealyang** [comment]
生产环境由于最近忙，还真的一直没有测，但是webpack的配置已经写好了，说白了就是将react打包出来而已，然后前端页面服务会根据环境（prod or dev）去判断是否起热更新，也就是后端服务并不需要做大改动，可能就是资源目录需要修改下。可以参照create-react-app来看下打包出来是什么样子，基本react开发出来打包后都那种套路
