### ISSUE TITLE
导入数据之后，注册用户没有任何反应？

### ISSUE THREAD

**Issue by Italic-2012** [Nealyang/React-Express-Blog-Demo#4]
![image](https://user-images.githubusercontent.com/24502019/32267506-75d323e2-bf26-11e7-9f1d-c100edd6f194.png)
导入的是这里的数据，难道错了？

**Comment by Nealyang** [comment]
![image](https://user-images.githubusercontent.com/9313216/32268278-4f64a516-bf29-11e7-8e44-11d0367d5c76.png)
最简单直白的方法就是你导入这个数据库了以后，进入到数据库去看看，有没有这些数据

**Comment by Italic-2012** [comment]
你这是BSON存储格式，跟注册没关系吧

**Comment by Nealyang** [comment]
所以你是连接数据库成功了？注册没有反应？

那么截图登录成功了是什么情况？

**Comment by Italic-2012** [comment]
![image](https://user-images.githubusercontent.com/24502019/32268392-da9010f8-bf29-11e7-944a-e5bb50ff9812.png)
![image](https://user-images.githubusercontent.com/24502019/32268427-009e4fb2-bf2a-11e7-8f49-6bf52cb85535.png)

**Comment by Nealyang** [comment]
注册后，users的collection有数据吗？

**Comment by Italic-2012** [comment]
![image](https://user-images.githubusercontent.com/24502019/32268627-d7c92886-bf2a-11e7-93e0-140d9db90fd0.png)
成功了！但是怎么进入管理后台？

**Comment by Nealyang** [comment]
因为进入管理后台是超级管理，所以超级管理，不可能是前端注册来的。是初始化数据库写入的。
1、 内置一个超级管理员，用户名、密码啥的
2、 看注册那部分nodejs代码，把注册的用户type设置为admin

**Comment by forturegrant** [comment]
![default](https://user-images.githubusercontent.com/30141935/32372761-317cc930-c0d1-11e7-8e90-dcd16aaf970e.png)



进了，谢谢解答！
