### ISSUE TITLE
启动后的界面进不了管理界面

### ISSUE THREAD

**Issue by wcl-git** [Nealyang/React-Express-Blog-Demo#50]
![image](https://user-images.githubusercontent.com/18394157/52838977-794faf00-312f-11e9-84c4-ea54e23df4cc.png)

**Comment by zhudongsheng** [comment]
你有源码吗？给我一份，我clone下来的代码前端页面都启动不了

**Comment by wcl-git** [comment]
代码没有改动的，只要你mongodb正常启动，就可以的，没有启动就会报错

在 2019-04-19 11:02:19，"zhudongsheng" <notifications@github.com> 写道：


你有源码吗？给我一份，我clone下来的代码前端页面都启动不了

**Comment by lmlmkp** [comment]
我的也走不了

**Comment by zhudongsheng** [comment]
你要什么样的源码？
------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>;
发送时间: 2019年4月30日(星期二) 晚上9:34
收件人: "Nealyang/React-Express-Blog-Demo"<React-Express-Blog-Demo@noreply.github.com>;
抄送: "淡悟"<1461879082@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [Nealyang/React-Express-Blog-Demo] 启动后的界面进不了管理界面 (#50)



代码没有改动的，只要你mongodb正常启动，就可以的，没有启动就会报错
 
 在 2019-04-19 11:02:19，"zhudongsheng" <notifications@github.com> 写道：
 
 
 你有源码吗？给我一份，我clone下来的代码前端页面都启动不了

**Comment by lmlmkp** [comment]
不用了，他给的启动方式有问题，分开启动就能走了，谢了




------------------ 原始邮件 ------------------
发件人: "zhudongsheng"<notifications@github.com>;
发送时间: 2019年5月5日(星期天) 下午3:34
收件人: "Nealyang/React-Express-Blog-Demo"<React-Express-Blog-Demo@noreply.github.com>;
抄送: "易湮"<1282788226@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [Nealyang/React-Express-Blog-Demo] 启动后的界面进不了管理界面 (#50)



你要什么样的源码？ 
 ------------------ 原始邮件 ------------------ 
 发件人: "notifications"<notifications@github.com>; 
 发送时间: 2019年4月30日(星期二) 晚上9:34 
 收件人: "Nealyang/React-Express-Blog-Demo"<React-Express-Blog-Demo@noreply.github.com>; 
 抄送: "淡悟"<1461879082@qq.com>; "Comment"<comment@noreply.github.com>;  
 主题: Re: [Nealyang/React-Express-Blog-Demo] 启动后的界面进不了管理界面 (#50) 
 
 
 
 代码没有改动的，只要你mongodb正常启动，就可以的，没有启动就会报错 
   
  在 2019-04-19 11:02:19，"zhudongsheng" <notifications@github.com> 写道： 
   
   
  你有源码吗？给我一份，我clone下来的代码前端页面都启动不了

**Comment by Nealyang** [comment]
> 不用了，他给的启动方式有问题，分开启动就能走了，谢了
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "zhudongsheng"<notifications@github.com>; 发送时间: 2019年5月5日(星期天) 下午3:34 收件人: "Nealyang/React-Express-Blog-Demo"<React-Express-Blog-Demo@noreply.github.com>; 抄送: "易湮"<1282788226@qq.com>; "Comment"<comment@noreply.github.com>; 主题: Re: [Nealyang/React-Express-Blog-Demo] 启动后的界面进不了管理界面 (#50) 你要什么样的源码？ ------------------ 原始邮件 ------------------ 发件人: "notifications"<notifications@github.com>; 发送时间: 2019年4月30日(星期二) 晚上9:34 收件人: "Nealyang/React-Express-Blog-Demo"<React-Express-Blog-Demo@noreply.github.com>; 抄送: "淡悟"<1461879082@qq.com>; "Comment"<comment@noreply.github.com>; 主题: Re: [Nealyang/React-Express-Blog-Demo] 启动后的界面进不了管理界面 (#50) 代码没有改动的，只要你mongodb正常启动，就可以的，没有启动就会报错 在 2019-04-19 11:02:19，"zhudongsheng" <notifications@github.com> 写道： 你有源码吗？给我一份，我clone下来的代码前端页面都启动不了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

#10
