### ISSUE TITLE
启动不了

### ISSUE THREAD

**Issue by lmlmkp** [Nealyang/React-Express-Blog-Demo#51]
![image](https://user-images.githubusercontent.com/32733901/57176633-b6a11e80-6e8c-11e9-9646-24b0b2f1fc14.png)
server启动出错

**Comment by lmlmkp** [comment]
解决了，分开运行，先服务端再客户端

**Comment by Nealyang** [comment]
> 解决了，分开运行，先服务端再客户端

#10
