### ISSUE TITLE
mac运行正常，windows下有问题是怎么回事啊

### ISSUE THREAD

**Issue by mrcoolkwok** [Nealyang/React-Express-Blog-Demo#53]
macbook是没问题的，windows下运行，前端页面出来了，但是请求数据有问题，数据库都确定正常运行了。

Error: connect ECONNREFUSED 127.0.0.1:3030
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react_express_blog@1.0.0 watch-client: `cross-env NODE_ENV=development node server/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react_express_blog@1.0.0 watch-client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\koo\AppData\Roaming\npm-cache\_logs\2019-07-04T01_51_30_650Z-debug.log

> react_express_blog@1.0.0 start-dev-api E:\exersice\项目案例\React-Express-Blog-Demo-master
> nodemon --watch server/api server/api/index.js

[nodemon] 1.17.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: E:\exersice\项目案例\React-Express-Blog-Demo-master\server\api/**/*
[nodemon] starting `node server/api/index.js`
数据库连接成功
===> api server is running at localhost:3030

**Comment by Nealyang** [comment]
#51
