### ISSUE TITLE
怎么导入数据呢

### ISSUE THREAD

**Issue by 545682879** [Nealyang/React-Express-Blog-Demo#6]
把下载下来的文件直接放到 C:\data\db 下可以吗？

**Comment by Nealyang** [comment]
百度 mongoimport

**Comment by thunderthunder** [comment]
这个问题我也折腾了半天，首先用mongoimport去试，结果这个命令无法导入BSON文件，而且让我钻了牛角尖，最后我用mongorestore -d blog C:\blog就成功了，C:\blog就是我下载的网盘上的blog文件夹，希望对你有用
