### ISSUE TITLE
网络请求错误，不知道怎么解决

### ISSUE THREAD

**Issue by 734976581** [Nealyang/React-Express-Blog-Demo#7]
导入bson到mongodb、npm install后，npm start  跳转到浏览器，出现网络请求错误，没有显示对应的文章，同时也登陆不了

**Comment by Nealyang** [comment]
具体报错信息粘贴出来下，确定本机端口未占用，后端正常跑起来了？

**Comment by 734976581** [comment]
![image](https://user-images.githubusercontent.com/26241448/33003072-5bcb92c8-cdf3-11e7-94f7-517fcdb0428c.png)

**Comment by 734976581** [comment]
页面显示出来  跳出网络请求错误  没有显示文章

**Comment by forturegrant** [comment]
"start": "concurrently \"npm run start-dev-api\" \"npm run watch-client\""

先连接数据库，

**Comment by Nealyang** [comment]
我开发是在Mac下开发的，所以这么直接起没问题，window下把start中的命令分两个DOS窗口分别启动

**Comment by 734976581** [comment]
感谢，已经跑起来了    还以为npm start就可以启动了  原来还是系统差异

**Comment by Nealyang** [comment]
对的，这边我一直没有win可以测试，最近忙也就忽视了，如果么有别的问题，这个issue我就关闭了哦
