### ISSUE TITLE
把数据写入数据库，重新加载是如何把数据重新渲染到前端界面上的

### ISSUE THREAD

**Issue by forturegrant** [Nealyang/React-Express-Blog-Demo#8]

**Comment by Nealyang** [comment]
重新加载是如何把数据渲染到前端界面，这个问的是，如果请求数据？请求数据触发的条件？还是、、、？

**Comment by forturegrant** [comment]
就是页面刷新重新加载

**Comment by Nealyang** [comment]
在react对应的生命周期中去触发请求不就可以了么

**Comment by forturegrant** [comment]
生命周期？触发什么请求？可以举个例子吗

**Comment by forturegrant** [comment]
生命周期是指componentWillMount(),componentDidMount()这些吧，那在哪个触发请求

**Comment by Nealyang** [comment]
对的，这些react的基础知识可以多多看看博客，比较基础也是非常重要的
