### ISSUE TITLE
拉下来执行npm install  报了一些错  没管它  然后npm start就报这个错了

### ISSUE THREAD

**Issue by stovd** [Nealyang/React-Express-Blog-Demo#9]
![image](https://user-images.githubusercontent.com/20417236/33068033-f666fd5c-ceea-11e7-97b7-6c710bd47684.png)

**Comment by yaderick** [comment]
一样的

**Comment by Nealyang** [comment]
node的版本是多少？开发版本为7.9

**Comment by zhongtingbing** [comment]
npm start 报错误，F:\node_boke\React-Express-Blog-Demo\node_modules\http-proxy\lib\http-F:\node_boke\React-Express-Blog-Demo\node_modules\http-proxy\lib\http-proxy\index.js:119
    throw err;
    ^

Error: connect ECONNREFUSED 127.0.0.1:3030
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react_express_blog@1.0.0 watch-client: `cross-env NODE_ENV=development node ./server/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react_express_blog@1.0.0 watch-client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zhongtingbing\AppData\Roaming\npm-cache\_logs\2017-11-30T16_11_03_358Z-debug.log

> react_express_blog@1.0.0 start-dev-api F:\node_boke\React-Express-Blog-Demo
> nodemon --watch server/api server/api/index.js

[nodemon] 1.12.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: F:\node_boke\React-Express-Blog-Demo\server\api/**/*
[nodemon] starting `node server/api/index.js`
(node:6692) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html
#use-mongo-client
数据库连接成功
===> api server is running at 127.0.0.1:3030
请问这是什么问题，怎样解决

**Comment by zhongtingbing** [comment]
我也报了他的错误，是因为  let response = yield call(get,'/user/userInfo');这句代码抛的异常，因该是数据库没user的原因吧
